frr version 10.0
hostname h1edgesw1a
service integrated-vtysh-config

interface eth1
 ip address 10.1.10.0/31
 description DX to AWS DEV DXGW

! Originate some prefixes
! TODO - remove once other originating peers connected
ip route 10.200.0.0/16 Null0
ip route 10.201.0.0/16 Null0
ip route 10.202.0.0/16 Null0

! Allow-all route map
route-map ALLOW-ALL permit 10

! Route everything
router bgp 65051
 neighbor 10.1.10.1 remote-as 65100
 description DX to AWS DEV DXGW

 ! allow everything
 neighbor 10.1.10.1 route-map ALLOW-ALL in
 neighbor 10.1.10.1 route-map ALLOW-ALL out

 ! send the networks
 network 10.200.0.0/16
 network 10.201.0.0/16
 network 10.202.0.0/16
