frr version 10.0
hostname h1edgesw1a
service integrated-vtysh-config

! Allow-all route map
route-map ALLOW-ALL permit 10

!
!   AWS VRF
!
interface eth1
 ip address 10.1.10.0/31
 description DX to AWS DEV DXGW
end

interface eth3
 ip address 10.1.10.10/31
 description h1edgengfw
end

! Route everything
router bgp 65051 vrf AWS-DEV
 bgp router-id 10.1.10.0
 neighbor 10.1.10.1 remote-as 65100
 description DX to AWS DEV DXGW
 neighbor 10.1.10.11 remote-as 64900
 description H1 Edge NGFW

 ! allow everything
 neighbor 10.1.10.1 route-map ALLOW-ALL in
 neighbor 10.1.10.1 route-map ALLOW-ALL out
 neighbor 10.1.10.11 route-map ALLOW-ALL in
 neighbor 10.1.10.11 route-map ALLOW-ALL out
exit


!
!   B2B VRF
!
interface eth2
 ip address 10.1.10.2/31
 description ER to B2B DEV
end

interface eth4
 ip address 10.1.10.12/31
 description h1edgengfw
end

router bgp 65052 vrf B2B-DEV
 bgp router-id 10.1.10.2
 neighbor 10.1.10.3 remote-as 65200
 description ER to B2B DEV
 neighbor 10.1.10.13 remote-as 64900
 description H1 Edge NGFW

 ! allow everything
 neighbor 10.1.10.3 route-map ALLOW-ALL in
 neighbor 10.1.10.3 route-map ALLOW-ALL out
 neighbor 10.1.10.13 route-map ALLOW-ALL in
 neighbor 10.1.10.13 route-map ALLOW-ALL out
exit
