frr version 10.0
hostname h1edgengfw
service integrated-vtysh-config

! Allow-all route map
route-map ALLOW-ALL permit 10

interface eth1
 ip address 10.1.10.11/31
 description AWS-DEV
exit

interface eth2
 ip address 10.1.10.13/31
 description B2B-DEV
exit

! Generate NATed route
ip route 192.168.200.0/24 Null0 vrf NGFW-DEV

! Generate RFC 1918 summary routes
ip route 10.0.0.0/8 eth1 vrf NGFW-DEV
ip route 172.16.0.0/12 eth1 vrf NGFW-DEV
ip route 192.168.0.0/16 eth1 vrf NGFW-DEV

! PLs for restricting overlapping advertisement
ip prefix-list AWS-OUT seq 10 permit 192.168.200.0/24

ip prefix-list B2B-OUT seq 10 permit 10.0.0.0/8
ip prefix-list B2B-OUT seq 20 permit 172.16.0.0/12
ip prefix-list B2B-OUT seq 30 permit 192.168.0.0/16

! RMs for restricting overlapping advertisement
route-map AWS-OUT permit 10
 match ip address prefix-list AWS-OUT
exit

route-map B2B-OUT permit 10
 match ip address prefix-list B2B-OUT
exit

! Route everything
router bgp 64900 vrf NGFW-DEV
 bgp router-id 10.1.10.11
 neighbor 10.1.10.10 remote-as 65051
 description AWS-DEV
 neighbor 10.1.10.12 remote-as 65052
 description B2B-DEV

 ! allow everything
 neighbor 10.1.10.10 route-map ALLOW-ALL in
 neighbor 10.1.10.10 route-map AWS-OUT out
 neighbor 10.1.10.12 route-map ALLOW-ALL in
 neighbor 10.1.10.12 route-map B2B-OUT out

 address-family ipv4 unicast
  network 192.168.200.0/24
  network 10.0.0.0/8
  network 172.16.0.0/12
  network 192.168.0.0/16
 exit address-family
exit
