frr version 10.0
frr defaults datacenter
hostname leaf3
service integrated-vtysh-config

! Loopback for router ID
interface lo
  ip address 10.255.255.3/32
  description Loopback

! Uplink to spine1
interface eth1
  ip address 10.255.250.8/31
  description Underlay - spine1

! Uplink to spine2
interface eth2
  ip address 10.255.250.10/31
  description Underlay - spine2


! Flat routed underlay
router bgp 64603
  bgp router-id 10.255.255.3
  no bgp default ipv4-unicast
  
  ! ECMP across both spines
  maximum-paths 2

  ! Spine 1
  neighbor SPINE1 peer-group
  neighbor SPINE1 remote-as 64700
  neighbor 10.255.250.9 peer-group SPINE1

  ! Spine 2
  neighbor SPINE2 peer-group
  neighbor SPINE2 remote-as 64700
  neighbor 10.255.250.11 peer-group SPINE2

  address-family ipv4 unicast
    network 10.255.255.3/32

    neighbor SPINE1 activate
    neighbor SPINE2 activate

  exit-address-family

  address-family l2vpn evpn
    neighbor SPINE1 activate
    neighbor SPINE2 activate
  exit-address-family
