frr version 10.0
frr defaults datacenter
hostname spine1
service integrated-vtysh-config

! Loopback for router ID
interface lo
  ip address 10.255.255.10/32
  description Loopback

! Downlink to leaf1
interface eth1
  ip address 10.255.250.1/31
  description Underlay - leaf1

! Downlink to leaf2
interface eth2
  ip address 10.255.250.5/31
  description Underlay - leaf2

! Downlink to leaf3
interface eth3
  ip address 10.255.250.9/31
  description Underlay - leaf3


! Flat routed underlay
router bgp 64700
  bgp router-id 10.255.255.10
  no bgp default ipv4-unicast

  ! Leaf 1
  neighbor LEAF1 peer-group
  neighbor LEAF1 remote-as 64601
  neighbor 10.255.250.0 peer-group LEAF1

  ! Leaf 2
  neighbor LEAF2 peer-group
  neighbor LEAF2 remote-as 64602
  neighbor 10.255.250.4 peer-group LEAF2

  ! Leaf 3
  neighbor LEAF3 peer-group
  neighbor LEAF3 remote-as 64603
  neighbor 10.255.250.8 peer-group LEAF3

  address-family ipv4 unicast
    network 10.255.255.10/32
    
    neighbor LEAF1 activate
    neighbor LEAF2 activate
    neighbor LEAF3 activate
  
  exit address-family
