frr version 8.0
hostname dc3
service integrated-vtysh-config

interface eth1
 ip address 10.10.10.38/31
 description DCI - Hub 1

interface eth2
 ip address 10.10.10.40/31
 description DCI - Hub 2

ip route 10.90.0.0/16 Null0

route-map PREFER-HUB2-IN permit 10
 set local-preference 200

route-map DISFAVOR-HUB1-OUT permit 10
 set as-path prepend 65063 65063 65063

route-map ALLOW-ALL permit 10

router bgp 65063
 neighbor 10.10.10.39 remote-as 65052
 neighbor 10.10.10.41 remote-as 65051

 ! allow everything
 neighbor 10.10.10.39 route-map ALLOW-ALL in
 neighbor 10.10.10.39 route-map DISFAVOR-HUB1-OUT out
 neighbor 10.10.10.41 route-map PREFER-HUB2-IN in
 neighbor 10.10.10.41 route-map ALLOW-ALL out

 network 10.90.0.0/16
