frr version 8.0
hostname us-dxgw
service integrated-vtysh-config

! us-east-1
interface eth1
 ip address 10.10.10.0/31

! us-west-2
interface eth2
 ip address 10.10.10.2/31

! dc1
interface eth3
 ip address 10.10.10.4/31

! dc2
interface eth4
 ip address 10.10.10.6/31


router bgp 65100
 neighbor 10.10.10.1 remote-as 65101
 neighbor 10.10.10.3 remote-as 65102
 neighbor 10.10.10.5 remote-as 65052
 neighbor 10.10.10.7 remote-as 65051

 ! allow everything (fixes your policy issue)
 neighbor 10.10.10.1 route-map ALLOW-ALL-use1 in
 neighbor 10.10.10.1 route-map ALLOW-ALL-use1 out
 neighbor 10.10.10.3 route-map ALLOW-ALL-usw2 in
 neighbor 10.10.10.3 route-map ALLOW-ALL-usw2 out
 neighbor 10.10.10.5 route-map ALLOW-ALL-dc1 in
 neighbor 10.10.10.5 route-map ALLOW-ALL-dc1 out
 neighbor 10.10.10.7 route-map ALLOW-ALL-dc2 in
 neighbor 10.10.10.7 route-map ALLOW-ALL-dc2 out

route-map ALLOW-ALL-use1 permit 10
route-map ALLOW-ALL-usw2 permit 10
route-map ALLOW-ALL-dc1 permit 10
route-map ALLOW-ALL-dc2 permit 10