frr version 10.0
hostname dev-dxgw
service integrated-vtysh-config

interface eth1
 ip address 10.1.10.1/31
 description DX to h1edgesw1a

! Originate some prefixes (AWS regional networks)
! TODO - model CNEs, originate routes there
ip route 10.100.0.0/16 Null0
ip route 10.101.0.0/16 Null0
ip route 10.102.0.0/16 Null0

! Allow-all route map
route-map ALLOW-ALL permit 10

! Route everything
router bgp 65100
 neighbor 10.1.10.0 remote-as 65051
 description DX to h1edgesw1a

 ! allow everything
 neighbor 10.1.10.0 route-map ALLOW-ALL in
 neighbor 10.1.10.0 route-map ALLOW-ALL out

 ! send the networks
 network 10.100.0.0/16
 network 10.101.0.0/16
 network 10.102.0.0/16
