frr version 8.0
hostname dc2
service integrated-vtysh-config

interface eth1
 ip address 10.10.10.34/31
 description DCI - Hub 1

interface eth2
 ip address 10.10.10.36/31
 description DCI - Hub 2

ip route 10.80.0.0/16 Null0

router bgp 65062
 neighbor 10.10.10.35 remote-as 65052
 neighbor 10.10.10.37 remote-as 65051

 ! allow everything
 neighbor 10.10.10.35 route-map ALLOW-ALL in
 neighbor 10.10.10.35 route-map ALLOW-ALL out
 neighbor 10.10.10.37 route-map ALLOW-ALL in
 neighbor 10.10.10.37 route-map ALLOW-ALL out

 network 10.80.0.0/16

route-map ALLOW-ALL permit 10