frr version 8.0
hostname hub1
service integrated-vtysh-config

interface eth1
 ip address 10.10.10.5/31
 description US AWS DXGW

interface eth2
 ip address 10.10.10.20/31
 description Hub 2 DCI

interface eth3
 ip address 10.10.10.31/31
 description DCI - DC1

interface eth4
 ip address 10.10.10.35/31
 description DCI - DC2

interface eth5
 ip address 10.10.10.39/31
 description DCI - DC3

ip route 10.60.0.0/16 Null0

router bgp 65052
 neighbor 10.10.10.4 remote-as 65100
 neighbor 10.10.10.21 remote-as 65051
 neighbor 10.10.10.30 remote-as 65061
 neighbor 10.10.10.34 remote-as 65062
 neighbor 10.10.10.38 remote-as 65063

 ! allow everything
 neighbor 10.10.10.4 route-map ALLOW-ALL in
 neighbor 10.10.10.4 route-map ALLOW-ALL out
 neighbor 10.10.10.21 route-map ALLOW-ALL in
 neighbor 10.10.10.21 route-map ALLOW-ALL out
 neighbor 10.10.10.30 route-map ALLOW-ALL in
 neighbor 10.10.10.30 route-map ALLOW-ALL out
 neighbor 10.10.10.34 route-map ALLOW-ALL in
 neighbor 10.10.10.34 route-map ALLOW-ALL out
 neighbor 10.10.10.38 route-map ALLOW-ALL in
 neighbor 10.10.10.38 route-map ALLOW-ALL out

 network 10.60.0.0/16

route-map ALLOW-ALL permit 10