frr version 8.0
hostname hub2
service integrated-vtysh-config

interface eth1
 ip address 10.10.10.7/31
 description US AWS DXGW

interface eth2
 ip address 10.10.10.21/31
 description Hub 1 DCI

interface eth3
 ip address 10.10.10.33/31
 description DCI - DC1

interface eth4
 ip address 10.10.10.37/31
 description DCI - DC2

interface eth5
 ip address 10.10.10.41/31
 description DCI - DC3

ip route 10.50.0.0/16 Null0

router bgp 65051
 neighbor 10.10.10.6 remote-as 65100
 neighbor 10.10.10.20 remote-as 65052
 neighbor 10.10.10.32 remote-as 65061
 neighbor 10.10.10.36 remote-as 65062
 neighbor 10.10.10.40 remote-as 65063

 ! allow everything
 neighbor 10.10.10.6 route-map ALLOW-ALL in
 neighbor 10.10.10.6 route-map ALLOW-ALL out
 neighbor 10.10.10.20 route-map ALLOW-ALL in
 neighbor 10.10.10.20 route-map ALLOW-ALL out
 neighbor 10.10.10.32 route-map ALLOW-ALL in
 neighbor 10.10.10.32 route-map ALLOW-ALL out
 neighbor 10.10.10.36 route-map ALLOW-ALL in
 neighbor 10.10.10.36 route-map ALLOW-ALL out
 neighbor 10.10.10.40 route-map ALLOW-ALL in
 neighbor 10.10.10.40 route-map ALLOW-ALL out

 network 10.50.0.0/16

route-map ALLOW-ALL permit 10