frr version 8.0
hostname us-west-2
service integrated-vtysh-config

interface eth1
 ip address 10.10.10.3/31
 description US AWS DXGW

interface eth2
  ip address 10.10.10.22/31
  description AWS Full Mesh - us-east-1 <> us-west-2

ip route 10.120.0.0/16 Null0

router bgp 65102
 neighbor 10.10.10.2 remote-as 65100
 neighbor 10.10.10.23 remote-as 65101

 ! allow everything (fixes your policy issue)
 neighbor 10.10.10.2 route-map ALLOW-ALL in
 neighbor 10.10.10.2 route-map ALLOW-ALL out
 neighbor 10.10.10.23 route-map ALLOW-ALL in
 neighbor 10.10.10.23 route-map ALLOW-ALL out

 network 10.120.0.0/16

route-map ALLOW-ALL permit 10