frr version 10.0
hostname dev-b2b
service integrated-vtysh-config

interface eth1
 ip address 10.1.10.3/31
 description ER to h1edgesw1a

! Originate some prefixes (B2B networks)
ip route 10.200.0.0/24 Null0

! Allow-all route map
route-map ALLOW-ALL permit 10

! Route everything
router bgp 65200
 neighbor 10.1.10.2 remote-as 65052
 description ER to h1edgesw1a

 ! allow everything
 neighbor 10.1.10.2 route-map ALLOW-ALL in
 neighbor 10.1.10.2 route-map ALLOW-ALL out

 ! send the networks
 address-family ipv4 unicast
  network 10.200.0.0/24
 exit address-family
exit
